# Railway deployment configuration
[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "cd server && npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production.variables]
  NODE_ENV = "production"